---
params:
  gene_panel: "TO_BE_SET"
  segmentation_qc_path: "TO_BE_SET"


title: "Report: Segmentation QC for gene_panel `r params$gene_panel`"
author: "Daria Buszta"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
library(Seurat)
library(ggplot2)
library(dplyr)
```

```{r}
segmentation_qc <- read.csv(params$segmentation_qc_path)
```

# Generate QC plots

number of cells
```{r, fig.height=7}

segmentation_qc$segmentation <- as.factor(all_data$segmentation)

ggplot(all_data, aes(x = tissue, y = cells, fill = segmentation)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  theme(
    axis.title = element_text(size = 26),       # Increase axis title font size
    axis.text = element_text(size = 24),        # Increase axis text font size
    legend.text = element_text(size = 24),      # Increase legend text font size
    plot.title = element_text(size = 28)        # Increase plot title font size
  ) +
  #scale_y_log10() +
  labs(title = NULL, y = "Number of Cells")

```
singlets
```{r, fig.height=7}

ggplot(all_data, aes(x = tissue, y = singlets, fill = segmentation)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  theme(
    axis.title = element_text(size = 26),       # Increase axis title font size
    axis.text = element_text(size = 24),        # Increase axis text font size
    legend.text = element_text(size = 24),      # Increase legend text font size
    plot.title = element_text(size = 28)        # Increase plot title font size
  ) +
  #scale_y_log10() +
  labs(title = NULL, y = "% of Singlets")

```
rejects
```{r, fig.height=7}

ggplot(all_data, aes(x = tissue, y = rejects, fill = segmentation)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  theme(
    axis.title = element_text(size = 26),       # Increase axis title font size
    axis.text = element_text(size = 24),        # Increase axis text font size
    legend.text = element_text(size = 24),      # Increase legend text font size
    plot.title = element_text(size = 28)        # Increase plot title font size
  ) +
  #scale_y_log10() +
  labs(title = NULL, y = "% of Rejects")

```
mean_nCount
```{r, fig.height=7}

ggplot(all_data, aes(x = tissue, y = mean_ncount, fill = segmentation)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  theme(
    axis.title = element_text(size = 26),       # Increase axis title font size
    axis.text = element_text(size = 24),        # Increase axis text font size
    legend.text = element_text(size = 24),      # Increase legend text font size
    plot.title = element_text(size = 28)        # Increase plot title font size
  ) +
  #scale_y_log10() +
  labs(title = NULL, y = "mean_nCount")

```
mean_nFeature
```{r, fig.height=7}

ggplot(all_data, aes(x = tissue, y = mean_nfeature, fill = segmentation)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  theme(
    axis.title = element_text(size = 26),       # Increase axis title font size
    axis.text = element_text(size = 24),        # Increase axis text font size
    legend.text = element_text(size = 24),      # Increase legend text font size
    plot.title = element_text(size = 28)        # Increase plot title font size
  ) +
  #scale_y_log10() +
  labs(title = NULL, y = "mean_nFeature")

```
