output_path: results

containers:
  r:
  10x:
  baysor:
  proseg:

experiments: experiments.yml

reprocess:
  level: 1
  _threads: 16
  _memory: 64

segmentation:
  methods:
    - 10x
    - baysor

  10x:
    expansion-distance:
      - 0
      - 5
      - 15

    localcores: 16
    localmem: 64
    _other_options:

  baysor:
    _config: "workflow/configs/baysor_xenium.toml"
    _threads: 16
    _memory: 600
    _other_options:

  _normalisation:
    _threads: 16
    _memory: 64

standard_seurat_analysis:
  qc:
    min_counts: 10
    min_features: 5
    max_counts: Inf
    max_features: Inf
    min_cells: 5

  dim_reduction:
    n_dims: 50

  clustering:
    resolution: 0.8

# just a plan, will be adjusted
cell-type-annotation:
  approaches:
    - reference-based
    - marker-based

  reference-based: # or reference-based-methods
    - RCTD
    - SingleR
    - Seurat
    - TANGRAM
    - XGBoost

  references:
    - matching-NSCLC
    - external-NSCLC
    - matching-breast
    - external-breast

  matching-annotation-levels: # mb, not exclusively for matching reference.
    - Level1
    - Level2
    - Level3
    - Level4

domain-identification:
  methods:
    - BANKSY
    - spatial-graph

  BANKSY:
    alpha: 0.5
    n_dims: 20

  spatial-graph:
    k_knn: 20
    radius: 30
