output_path: results

containers:
  r:
  10x:
  baysor:
  proseg:
  segger:

experiments: experiments.yml

reprocess:
  level: 1
  _threads: 16
  _memory: 64

segmentation:
  methods:
    - 10x
    - baysor
    - proseg
    - segger

  10x:
    expansion-distance:
      - 0
      - 5
      - 15

    localcores: 16
    localmem: 64
    _other_options:

  baysor:
    _config: "workflow/configs/baysor_xenium.toml"
    _threads: 1
    _memory: 200
    _other_options:

  proseg:
    _threads: 16
    _memory: 100
    _other_options:

  segger:
    preprocess:
      tile_width: 200
      tile_height: 200
      _threads: 8
      _other_options:

    train:
      accelerator: "cuda"
      devices: 1
      max_epochs: 200
      batch_size: 4
      _threads: 4
      _other_options:

  _normalisation:
    _threads: 16
    _memory: 64

standard_seurat_analysis:
  _future_globals_maxSize: 1

  qc:
    min_counts: 10
    min_features: 5
    max_counts: Inf
    max_features: Inf
    min_cells: 5

  dim_reduction:
    n_dims: 50

  clustering:
    resolution: 0.8

cell_type_annotation:
  reference_based:
    methods:
      - rctd
      - singler
      - seurat
      - tangram
      - xgboost

    modes:
      - single_cell
      - cluster

    rctd:
      # Min UMI in xenium cells to consider cell for sigma extimation (sigma of Log-Poisson distribution).
      UMI_min_sigma:
        - 100 # low UMI in single-cell mode
        - 300 # higher UMI in cluster mode

      _threads: 20
      _other_options:

    singler:
      # Use differentially expressed genes.
      genes: "de"

      # Test to use for DEA.
      de_method: "t"

      aggr_ref: True

      aggr_args:
        rank: 50
        power: 0.7

      _other_options:

    seurat:
      _other_options:

    tangram:
      _other_options:

    xgboost:
      _other_options:

  # marker_based: # placeholder

domain-identification: # placeholder
  methods:
    - BANKSY
    - spatial-graph

  BANKSY:
    alpha: 0.5
    n_dims: 20

  spatial-graph:
    k_knn: 20
    radius: 30
