_base_path: /path/to/raw/data

diseases_1:
  _cell_type_annotation:
    reference_based:
      # Empty path (either `None` or "") indicates that the corresponding reference is unavailable.
      # Please do not comment out sub-dictionaries.
      matched_reference:
        path: /path/to/reference
        levels:
          -

        # Minimum number of cells required per cell type. Can be decreased for smaller references.
        cell_min_instance: 25

      external_reference:
        path: /path/to/reference
        levels:
          -

        # Minimum number of cells required per cell type. Can be decreased for smaller references.
        cell_min_instance: 25

    # marker_based: # placeholder

  gene_panel_1:
    _gene_panel_file: /path/to/or/name/of/gene/panel/file

    _qc:
      # Comment out any of them if they are the same as the global QC thresholds.
      min_counts: 10
      min_features: 5
      max_counts: Inf
      max_features: Inf
      min_cells: 5

    donor_1: sample_1
    donor_2:
      - sample_2
      - sample_3
