executor: slurm
jobs: 500

default-resources:
  slurm_account: your_account
  slurm_partition: cpu
  threads: 1
  mem_mb: 5120
  runtime: 1440

set-resources:
  runBaysor:
    runtime: 4320
  adjustBaysorResults:
    mem_mb: max(input.size_mb * 10, 2048)
  runProseg:
    runtime: 4320
