executor: slurm
jobs: 500

default-resources:
  slurm_account: your_account
  slurm_partition: cpu
  threads: 1
  mem_mb: 5120 * attempt
  runtime: 1440

set-resources:
  runBaysor:
    runtime: 4320
  runProseg:
    runtime: 4320
  runReferenceBasedRCTD:
    runtime: 4320
  runSplitFullyPurified:
    runtime: 2880
